server:
  port: 8091
  servlet:
    context-path: /weather-persistence

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ENC(AQ90BEl4kjQqnEnwgBcnq+R4lHvrsF9bpHLtpqYfr11pT7PjalOGbpfu5fzazjBUHOPABz6ZlQF9jq1lU1QHQA==)
      secret-key: ENC(nNMtnKLivIWm2gaxo2/9u4uhrsfpi/Q3OvNNO8aKAgnBLCM8TVe5/6a4jY5clna/4zAR2Li9KymhdAAs0qmK2H6jd3cgrcYF8q0DHt3OxyI=)
    stack:
      auto: false

aws:
  sqs:
    weather-queue: https://sqs.us-east-2.amazonaws.com/267356554041/weather-persistence-command

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-standalone:3306/test
    username: sa
    password: ENC(Cfv16D9mgvHALgLBmK7n+tzGdBl+0z2R6n6hGTpOyTfXKtuDy+nB1sHdoDlDFapU)
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jasypt:
  encryptor:
    password: <INSERT_PASSWORD>
